### ISSUE TITLE
Value Conversion Error

### ISSUE THREAD

**Issue by scnerd** [change-engine/terraform-provider-slack-app#126]
Hi, I'm attempting to use this provider to update a Slack app I built manually. To start with, I copy-pasted the JSON from the Slack app management UI:

```hcl
resource "slack-token_refresh" "deployment_token" {}

resource "slack-app_manifest" "bot" {
  manifest = <<EOF
{
...
}
EOF
}
```

A plan shows only "whitespace changes"; it decides to try to update the value anyway, but all the data it sees as the manifest is exactly what's already in Slack and so it should work just fine.

Instead, I get the following error:
```
╷
│ Error: Value Conversion Error
│
│   with slack-app_manifest.bot,
│   on resources.slack.tf line 3, in resource "slack-app_manifest" "bot":
│    3: resource "slack-app_manifest" "bot" {
│
│ An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:
│
│ unhandled unknown value
╵
```

If I enable `TF_LOG=DEBUG`, I see the following, not sure it adds much:
```
slack-app_manifest.bot: Modifying... [id=***]
2024-05-22T14:12:31.706-0700 [INFO]  Starting apply for slack-app_manifest.bot
2024-05-22T14:12:31.706-0700 [DEBUG] skipping FixUpBlockAttrs
2024-05-22T14:12:31.706-0700 [DEBUG] slack-app_manifest.bot: applying the planned Update change
2024-05-22T14:12:31.707-0700 [DEBUG] State storage *remote.State declined to persist a state snapshot
2024-05-22T14:12:31.707-0700 [ERROR] vertex "slack-app_manifest.bot" error: Value Conversion Error
```

**Comment by scnerd** [comment]
I've never done TF providers before, but I'm taking a stab at opening a PR for this.

I installed the module locally and ran `go mod tidy`, which seems to have version-bumped go. Besides adding a few other debug statements, I didn't change anything else, and it seems to be working now. Might just be a version thing.

There does seem to be a separate issue that I can't access the app's credentials since this is only returned by the API during creation, and can't be obtained later, so it's impossible to fetch for a pre-existing app. That's unrelated and AFAIK an issue with the API, not the provider.

**Comment by BarnabyShearer** [comment]
Thank you for reporting. I have run `go mod tidy` and done a new release which will hopefully summerly work.

I am afraid you are correct that the API only gives credentials once.
