### ISSUE TITLE
Error: Incompatible provider version

### ISSUE THREAD

**Issue by madisettisunil** [change-engine/terraform-provider-slack-app#87]
Got stuck in terraform init stage. Any help would be much appreciated. Looks like no compatible versions of provider found.

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/template...
- Finding change-engine/slack-token versions matching "~> 0.1"...
- Finding change-engine/slack-app versions matching "~> 0.1"...
- Installing hashicorp/template v2.2.0...
- Installed hashicorp/template v2.2.0 (signed by HashiCorp)
╷
│ Error: Incompatible provider version
│ 
│ No compatible versions of provider registry.terraform.io/change-engine/slack-app were found.
╵

╷
│ Error: Incompatible provider version
│ 
│ No compatible versions of provider registry.terraform.io/change-engine/slack-token were found.

**Comment by BarnabyShearer** [comment]
I have just confirmed I can still install fine on fresh machines. Can you run `terraform -v` to help diagose the issue.
My output is (but anything > v1 on all common OS/Arch should just work)
```
terraform -v
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/change-engine/slack-app v0.1.0
+ provider registry.terraform.io/change-engine/slack-token v0.1.3
```

**Comment by BarnabyShearer** [comment]
This is in a directory containing a single .tf file:
```
terraform {
  required_providers {
    slack-token = {
      source  = "change-engine/slack-token"
      version = "~> 0.1"
    }
    slack-app = {
      source  = "change-engine/slack-app"
      version = "~> 0.1"
    }
  }
}
```
